/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ClinicRouteImport } from './routes/clinic'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as RedCarpetRouteImport } from './routes/red-carpet'
import { Route as ShopRouteImport } from './routes/shop'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ClinicRoute = ClinicRouteImport.update({
  id: '/clinic',
  path: '/clinic',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const RedCarpetRoute = RedCarpetRouteImport.update({
  id: '/red-carpet',
  path: '/red-carpet',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/clinic': typeof ClinicRoute
  '/contact': typeof ContactRoute
  '/red-carpet': typeof RedCarpetRoute
  '/shop': typeof ShopRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/clinic': typeof ClinicRoute
  '/contact': typeof ContactRoute
  '/red-carpet': typeof RedCarpetRoute
  '/shop': typeof ShopRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/clinic': typeof ClinicRoute
  '/contact': typeof ContactRoute
  '/red-carpet': typeof RedCarpetRoute
  '/shop': typeof ShopRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/$' | '/about' | '/clinic' | '/contact' | '/red-carpet' | '/shop'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$' | '/about' | '/clinic' | '/contact' | '/red-carpet' | '/shop'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/about'
    | '/clinic'
    | '/contact'
    | '/red-carpet'
    | '/shop'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AboutRoute: typeof AboutRoute
  ClinicRoute: typeof ClinicRoute
  ContactRoute: typeof ContactRoute
  RedCarpetRoute: typeof RedCarpetRoute
  ShopRoute: typeof ShopRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinic': {
      id: '/clinic'
      path: '/clinic'
      fullPath: '/clinic'
      preLoaderRoute: typeof ClinicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/red-carpet': {
      id: '/red-carpet'
      path: '/red-carpet'
      fullPath: '/red-carpet'
      preLoaderRoute: typeof RedCarpetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AboutRoute: AboutRoute,
  ClinicRoute: ClinicRoute,
  ContactRoute: ContactRoute,
  RedCarpetRoute: RedCarpetRoute,
  ShopRoute: ShopRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
