-- Customisable home-page images (hero, shop card, clinic card, store interior).
-- Private bucket like the other image buckets; public reads happen through
-- short-lived signed URLs generated by the server.

INSERT INTO storage.buckets (id, name, public)
VALUES ('site-images', 'site-images', false)
ON CONFLICT (id) DO NOTHING;

DROP POLICY IF EXISTS "Anyone can view site images" ON storage.objects;
CREATE POLICY "Anyone can view site images" ON storage.objects FOR SELECT TO anon, authenticated USING (bucket_id = 'site-images');

DROP POLICY IF EXISTS "Admins can upload site images" ON storage.objects;
CREATE POLICY "Admins can upload site images" ON storage.objects FOR INSERT TO authenticated WITH CHECK (bucket_id = 'site-images' AND public.has_role(auth.uid(), 'admin'));

DROP POLICY IF EXISTS "Admins can update site images" ON storage.objects;
CREATE POLICY "Admins can update site images" ON storage.objects FOR UPDATE TO authenticated USING (bucket_id = 'site-images' AND public.has_role(auth.uid(), 'admin'));

DROP POLICY IF EXISTS "Admins can delete site images" ON storage.objects;
CREATE POLICY "Admins can delete site images" ON storage.objects FOR DELETE TO authenticated USING (bucket_id = 'site-images' AND public.has_role(auth.uid(), 'admin'));
